---
site:
  title: Red Hat Hardened Images
  url: https://github.com/rhpds/cy27-rh1-lb2062a-rhhi
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

antora:
  extensions:
    - require: /antora/lib/dev-mode.js
      enabled: true
    - require: '@andrew-jones/antora-tabs-extension'

output:
  dir: ./www
